# Generated by Django 3.2.6 on 2021-08-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_title', models.CharField(max_length=45)),
                ('admin_content', models.CharField(max_length=450)),
                ('hits', models.SmallIntegerField(default=0)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450)),
                ('content', models.CharField(max_length=500)),
                ('hits', models.SmallIntegerField(default=0)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.admin')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'boards',
            },
        ),
    ]
