# Generated by Django 3.2.6 on 2021-08-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.admin'),
        ),
    ]
