# Generated by Django 3.2.6 on 2021-08-17 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_admin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
