# Generated by Django 3.2.6 on 2021-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210817_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password',
            field=models.TextField(default=None),
        ),
    ]
