# Generated by Django 3.2.6 on 2021-08-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_board_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
