# Generated by Django 3.2.6 on 2021-08-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_board_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
