# Generated by Django 3.2.6 on 2021-08-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.tag'),
        ),
    ]
