# Generated by Django 3.2.6 on 2021-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_alter_board_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
